import React, { useState } from 'react';
import jsPDF from 'jspdf';
import { useCognitiveStore } from '../../stores/cognitiveStore';
import { Download, FileText, Loader2 } from 'lucide-react';

export const ClinicalExport: React.FC = () => {
  const [isExporting, setIsExporting] = useState(false);
  const currentLoad = useCognitiveStore((state) => state.cognitiveLoadScore);

  const generatePDF = async () => {
    setIsExporting(true);
    
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // Styling Constants
      const margin = 20;
      let yPos = 20;

      // Header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(30, 41, 59); // slate-800
      doc.text('NeuroAdaptive Context Report', margin, yPos);
      
      yPos += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139); // slate-500
      doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, margin, yPos);
      
      yPos += 20;

      // Section 1: Executive Summary
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text('1. Observational Summary', margin, yPos);
      
      yPos += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105);
      const summaryText = "This report aggregates 7 days of behavioral telemetry, including keystroke dynamics, context-switching frequency, and self-reported masking intervals. It highlights periods of peak flow and specific triggers for cognitive friction.";
      const splitSummary = doc.splitTextToSize(summaryText, 170);
      doc.text(splitSummary, margin, yPos);
      
      yPos += 10 + (splitSummary.length * 5);

      // Section 2: Cognitive Telemetry
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text('2. Cognitive Telemetry (Sample Data)', margin, yPos);
      
      yPos += 10;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      
      // Mock Data Points for the Hackathon Demo
      const metrics = [
        `• Current Baseline Load: ${currentLoad}/100`,
        `• Peak Focus Window: 10:00 AM - 12:30 PM`,
        `• Primary Friction Trigger: Context Switching (Tab Navigation)`,
        `• Estimated Masking Cost: 4.5 hours/week`
      ];

      metrics.forEach(metric => {
        doc.text(metric, margin + 5, yPos);
        yPos += 8;
      });

      yPos += 10;

      // Strict Disclaimer Footer
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184); // slate-400
      
      const footerText = "DISCLAIMER: This document contains observational telemetry and self-reported data generated by the NeuroAdaptive OS. It is designed to facilitate self-advocacy and workflow optimization. This is observational data, not a diagnostic tool. It does not constitute medical advice.";
      const splitFooter = doc.splitTextToSize(footerText, 170);
      
      // Position at the bottom of the page
      doc.text(splitFooter, margin, 280);

      // Save the document
      doc.save(`NeuroAdaptive_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 w-full mt-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-slate-100 rounded-lg">
          <FileText className="w-5 h-5 text-slate-600" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-slate-800 tracking-wide">Data Export</h3>
          <p className="text-xs text-slate-500">Generate a structured report for HR or clinical context.</p>
        </div>
      </div>

      <button
        onClick={generatePDF}
        disabled={isExporting}
        className="w-full bg-slate-800 hover:bg-slate-900 text-white py-3 rounded-xl font-medium transition-colors disabled:opacity-50 flex justify-center items-center gap-2"
      >
        {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <><Download className="w-4 h-4" /> Export Observational PDF</>}
      </button>
    </div>
  );
};